import Head from 'next/head'
import Image from 'next/image'
import { AiOutlineInstagram } from 'react-icons/ai';
import { FaFacebook } from 'react-icons/fa';
import { BsLinkedin } from 'react-icons/bs';


export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <div className='container'>
          <section className='content'>
            <div className='text one-text'>
              <div className='main'>
                <h1>
                  Web Design. <br></br>
                  Android + iOS. <br></br>
                  Desktop Apps.
                </h1>
                <p>The one step shop for all your needs.</p>
                <div className='social-media'>
                <AiOutlineInstagram />
                <FaFacebook />
                <BsLinkedin />
                </div>
                <button className='cta'>Contact Us</button>
              </div>
            </div>
            <div className='image one-image'>
              <div className='imgcontainer'>
                <img src="/graphics/1.png" className='img'></img>
              </div>
            </div>
          </section>
      </div>
      
      <div className='container'>
        <section className='content'>
          <div className='image two-image'>
              <div className='imgcontainer'>
                <img src="/graphics/10.png" className='img img--small'></img>
              </div>
          </div>
          <div className='text two-text'>
            <div className='main info info--right'>
              <h1>
                Lorem ipsum.
              </h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
              <button className='learn-more'>Learn More</button>
            
            </div>
          </div>  
        </section>
      </div>

      <div className='container'>
        <section className='content'>
          <div className='text three-text'>
            <div className='main info info--left'>
              <h1>
                Lorem ipsum.
              </h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
              <button className='learn-more'>Learn More</button>
            </div>
          </div>
          <div className='image three-image'>
              <div className='imgcontainer'>
                <img src="/graphics/7.png" className='img img--small'></img>
              </div>
          </div> 
        </section>
      </div>

      <div className='container'>
        <section className='content'>
          <div className='image four-image'>
              <div className='imgcontainer'>
                <img src="/graphics/8.png" className='img img--small'></img>
              </div>
          </div>
          <div className='text four-text'>
            <div className='main info info--right'>
              <h1>
                Lorem ipsum.
              </h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
              <button className='learn-more'>Learn More</button>
            </div>
          </div>
        </section>
      </div>

      <div className='container'>
        <section className='content'>
          <div className='text five-text'>
            <div className='main info info--left'>
              <h1>
                Lorem ipsum.
              </h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
              <button className='learn-more'>Learn More</button>
            </div>
          </div>
          <div className='image five-image'>
              <div className='imgcontainer'>
                <img src="/graphics/9.png" className='img img--small'></img>
              </div>
          </div>
        </section>
      </div>

      <div className='footer'>
        <div className='footer__text text'>
          <div className='main info'>
            <h1>
              Lorem ipsum.
            </h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
          </div>
        </div>
        <div className='footer__img'>
            <div className='f-img-container'>
              <img src="/graphics/6.png" className='f-img'></img>
            </div>
        </div>
      </div>
      
    </>
  )
}
